version: '3.8'
services:
  srcbox-test-db:
    build: .
    container_name: srcbox-temp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5564:5432" # Maps the port of the database to 5444 on the host, I always forget which way round it is
    volumes:
      - ./init:/docker-entrypoint-initdb.d
